//
// Created by kehan on 2020/1/14.
//

#ifndef CELEX5_ROS_SRC_INTERFACE_CELEX5CONFIGURE_H_
#define CELEX5_ROS_SRC_INTERFACE_CELEX5CONFIGURE_H_

class CeleX5Configure {

};

#endif //CELEX5_ROS_SRC_INTERFACE_CELEX5CONFIGURE_H_
